### ISSUE TITLE
Always 0/0 images treated

### ISSUE THREAD

**Issue by Teyk0o** [evansnguyen/image-optimization#1]
Hi Evansnguyen !

I use you actions to my private project but when the action is executed the step with your actionis always 0/0.
There is how i use it :

      - name: 🗜️ Compression des images
        uses: evansnguyen/image-optimization@v1.0.0
        with:
          token: ${{ github.token }}
          file: 'assets'
          branch: 'main'
          commit-branch: 'prod'    
          commit-message: 'Github Action: Auto compress images'
          
Any idea to fix that ?

**Comment by philspaces** [comment]
@Teyk0o 
Can you share your folder structure and GH actions log please?

**Comment by Teyk0o** [comment]
Yeah for sure, on the image all folder outlined in red is the folder where image are.
![image](https://github.com/evansnguyen/image-optimization/assets/61880621/a78f2364-cd8e-478c-be90-a90f25e46f4d)

And there is my GH Actions log :

```
Run evansnguyen/image-optimization@v1.0.0
/usr/bin/docker run --name bedb46365bb6131a84c56a948d6b15b8f09f5_bcae6a --label 5bedb4 --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_FILE" -e "INPUT_BRANCH" -e "INPUT_COMMIT-BRANCH" -e "INPUT_COMMIT-MESSAGE" -e "INPUT_COMMITTER" -e "INPUT_DRYRUN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/TruffAdopt/TruffAdopt":"/github/workspace" 5bedb4:6365bb6131a84c56a948d6b15b8f09f5
0/0 ✔ Squoosh results:

Committer REST API ok
Committer account (github-actions)
Using branch prod
Committer head branch status ok
```

**Comment by philspaces** [comment]
@Teyk0o 

Can you please try replace the toke with this template? It looks like there is no img in assets folder on prod branch

```yml
name: Image optimization
on:
  workflow_dispatch:
  pull_request:

jobs:
  my_bot_job:
    runs-on: ubuntu-latest
    steps:
      - uses: evansnguyen/image-optimization@v1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }} // your secret
          file: 'assets' // try empty string to scan entire repo
          branch: 'next-release' // this should be your current branch with assets
          commit-branch: 'awesome/image-optimization'
```

**Comment by Teyk0o** [comment]
Ok but can you explain me how i can have my secret for ${{ secrets.ACCESS_TOKEN }} ?
Im a beginner with GH Actions.

**Comment by philspaces** [comment]
Gh secret is where you can define variables, it is encrypted so you can share it with other services. In the example variable name is ACCESS_TOKEN. To get this token you need to generate it follow this guide: https://catalyst.zoho.com/help/tutorials/githubbot/generate-access-token.html
Read more: https://docs.github.com/en/actions/security-guides/encrypted-secrets#about-encrypted-secrets

**Comment by Teyk0o** [comment]
Ok I tried but same problem :

```
Run evansnguyen/image-optimization@v1.0.0
/usr/bin/docker run --name bedb4d2994f0463ca4c479f1b0bfaa30434f8_735262 --label 5bedb4 --workdir /github/workspace --rm -e "INPUT_TOKEN" -e "INPUT_FILE" -e "INPUT_BRANCH" -e "INPUT_COMMIT-BRANCH" -e "INPUT_COMMIT-MESSAGE" -e "INPUT_COMMITTER" -e "INPUT_DRYRUN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e...
0/0 ✔ Squoosh results:
Committer REST API ok
Committer account Teyk0o
Using branch prod
Committer head branch status ok
```

The GH Actions : 

```
      - name: 🗜️ Compression des images
        uses: evansnguyen/image-optimization@v1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          file: ''
          branch: 'main'
          commit-branch: 'prod'
```
